name: Bump Semver
description: "bump the version in input with semantic version"

inputs:
  current_version:
    required: true
    type: string
    description: The current version
  semver:
    required: true
    type: string
    description: The semantic version

outputs:
  new_version:
    description: "New Version"
    value: ${{ steps.bump_version.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Bump version
      id: bump_version
      uses: actions/github-script@v6.3.3
      env:
        CURRENT_VERSION: ${{inputs.current_version}}
        SEMVER: ${{inputs.semver}}
      with:
        result-encoding: string
        script: |
          var { CURRENT_VERSION, SEMVER } = process.env
          var versions = LATEST_TAG.replace('v','').trim('.');

          var major = parseInt(versions[0]);
          var minor = parseInt(versions[1]);
          var patch = parseInt(versions[2].trim('-')[0]);
          var buildNumber = parseInt(versions[2].trim('-')[1]);

          var newVersion = "";

          if (SEMVER == 'major'){
            newVersion = 'v' + (major + 1) + '.0.0' 
          }
          if (SEMVER == 'minor'){
            newVersion = 'v' + major.toString() + (minor + 1) + '.0' 
          } 
          if (SEMVER == 'patch'){
            newVersion = 'v' + major.toString() + minor.toString() + (patch + 1)
          }
          if (SEMVER == 'buildNumber'){
            newVersion = 'v' + major.toString() + minor.toString() + patch.toString() + '-' + (buildNumber + 1)
          }
          if (SEMVER == 'skip'){
            newVersion = LATEST_TAG
          }
          return newVersion;


