name: Make Package
description: "Make a new package on GitHub"

inputs:
  username:
    required: true
    type: string
    description: Github Username
  github_token:
    required: true
    type: string
    description: Github Token
  branch:
    required: true
    type: string
    description: Repository branch


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}

#    TODO check if package exists

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: maven

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2

    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      shell: bash

    - uses: whelk-io/maven-settings-xml-action@v4
      with:
        repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/${{github.repository}}" }]'
        servers: '[{ "id": "github", "username": "${{inputs.username}}", "password": "${{ inputs.github_token }}" }]'


    - name: Deploy to GitHub Package Registry
      run: |
        REPO="github::default::https://maven.pkg.github.com/${{github.repository}}"
        mvn -B deploy -DaltReleaseDeploymentRepository="${REPO}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
